### ISSUE TITLE
Cant found content but the video Is available

### ISSUE THREAD

**Issue by scerviez** [bramaudi/fbdown#2]
{
    "error": true,
    "message": "Can't found content"
}

i try With This URL 

https://fbdown.now.sh/?url=https://fb.watch/83NeFAFCZo/

**Comment by bramaudi** [comment]
This problem has 2 possibilities:
1. Demo site request blocked by Facebook (Solution: try on your local machine/server)
2. Error accessing video URL, make sure it's publicly accessible (Try open fb.watch/blablah in Incognito Window in your browser first and make sure it can play without login)
